Q1) Power Method and Associated problems (2 marks)
i) Generate using code a random integer matrix C of size 4×3 and a matrix
A1 defined as A1 = CTC and workout its characteristic equation.
Using any software package, determine the eigenvalues and eigenvectors.
Deliverables: The matrices C and A1, the computation of the characteristic
equation, the eigenvalues and eigenvectors as obtained from
the package. (0.5 marks)

ii) Write a code in your chosen programming language to implement the
Power method and use it to derive the largest eigenvalue λ1 and corresponding
eigenvector x1 of A1. Find ˆx1 =
x1
∥x1∥2
. Compare the values
obtained in i) with these values.
Deliverables: The handwritten code that implements the Power method,
the first 10 iterates of eigenvalue generated by the algorithm and the
final λ1 and ˆx1 and a comment on the comparison. (0.5 marks)

iii) Write a code to construct matrix A2 = (A1− ˆx1ˆxT1
A1). Use the Power
method code written in ii) and use it to derive the largest eigenvalue
λ2 and corresponding eigenvector x2 of A2. Find ˆx2 =
x2
∥x2∥2
. Compare
the values obtained in i) with these values.
Deliverables: The first 10 iterates of λ2 and ˆx2 and a comment on the
comparison. (0.5 marks)

iv) Write a code to construct matrix A3 = (A1 − ˆx1ˆxT1
A1 − ˆ x2ˆxT2A1).
Use the Power method code written in ii) and use it to derive the
largest eigenvalue λ3 and corresponding eigenvector x3 of A3. Find
ˆx3 =
x3
∥x3∥2
. Compare the values obtained in i) with these values.
Deliverables: The first 10 iterates of λ3 and ˆx3 and a comment on the
comparison.

In [42]:
import numpy as np

matrixC = np.random.randint(0,10,size=(4,3))


print("Random Matrix C : \n", matrixC)


matrixCT = matrixC.transpose()

print("Transpose of Matrix C : \n",matrixCT)

matrixA1 = np.dot(matrixCT,matrixC)
print("Matrix A : \n",matrixA1)

eigenvalues, eigenvectors = np.linalg.eig(matrixA1)

print("Eigen values : ",np.round(eigenvalues,5))

print("Eigen Vector : \n",np.round(eigenvectors,5))

lambdaValues = np.poly(matrixA1)
print("lambda values : ",lambdaValues)

charEq = np.poly1d(lambdaValues)

print("characteristic equation : \n",charEq)


Random Matrix C : 
 [[4 0 8]
 [9 2 6]
 [7 1 7]
 [5 4 5]]
Transpose of Matrix C : 
 [[4 9 7 5]
 [0 2 1 4]
 [8 6 7 5]]
Matrix A : 
 [[ 45  73  62]
 [ 73 158 107]
 [ 62 107 105]]
Eigen values :  [280.61217   5.33446  22.05337]
Eigen Vector : 
 [[ 0.37639  0.90465  0.19987]
 [ 0.72617 -0.1541  -0.67002]
 [ 0.57534 -0.39733  0.71493]]
lambda values :  [     1.   -308.   7803. -33012.]
characteristic equation : 
    3       2
1 x - 308 x + 7803 x - 3.301e+04


In [75]:
import numpy as np

def power_method(matrix, max_iterations=10):
    n = matrix.shape[0]
    
    # Initialize a random vector as the initial guess for the eigenvector
    # x = np.random.rand(n)
    x = np.ones(n,dtype=int)
    
    for i in range(max_iterations):
        # Power iteration step
        y = np.dot(matrix, x)
        # print(f"x : { x }  &  y(matrix and x) dot product = ",y)

        # Extract the largest magnitude component of y
        eigenvalue = np.max(y)
        
        # Normalize the eigenvector
        x = y / eigenvalue
        
        # Print the current iterate and eigenvalue
        print(f"Iteration {i + 1}: Eigenvalue = {eigenvalue:.5f} X = {x}")
    
    # Return the largest eigenvalue and the corresponding eigenvector
    return eigenvalue, x

# Using the previously generated matrix A1
# A1 = np.array([[30, 15, 26], [15, 19, 18], [26, 18, 29]])
# print("A1 = ",matrixA1)

np.set_printoptions(precision=5, suppress=True)

# Run the power method
lambda1, x1 = power_method(matrixA1)


# Display the first 10 iterates of the eigenvalue
# print("\nFirst 10 iterates of eigenvalue:")
# print(lambda1)

# Normalize the corresponding eigenvector outside the function
x1_hat = x1 / np.linalg.norm(x1, 2)

# Display the final results
print("\nFinal Results:")
print(f"Largest Eigenvalue (λ1): {lambda1:.5f}")
print(f"Corresponding Eigenvector (x1): {x1}")
print(f"Normalized eigenvector (ˆx1): {x1_hat}")




Iteration 1: Eigenvalue = 338.00000 X = [0.53254 1.      0.81065]
Iteration 2: Eigenvalue = 283.61538 X = [0.5191  1.      0.79381]
Iteration 3: Eigenvalue = 280.83176 X = [0.51837 1.      0.79241]
Iteration 4: Eigenvalue = 280.62915 X = [0.51832 1.      0.7923 ]
Iteration 5: Eigenvalue = 280.61350 X = [0.51832 1.      0.79229]
Iteration 6: Eigenvalue = 280.61228 X = [0.51832 1.      0.79229]
Iteration 7: Eigenvalue = 280.61218 X = [0.51832 1.      0.79229]
Iteration 8: Eigenvalue = 280.61218 X = [0.51832 1.      0.79229]
Iteration 9: Eigenvalue = 280.61217 X = [0.51832 1.      0.79229]
Iteration 10: Eigenvalue = 280.61217 X = [0.51832 1.      0.79229]

Final Results:
Largest Eigenvalue (λ1): 280.61217
Corresponding Eigenvector (x1): [0.51832 1.      0.79229]
Normalized eigenvector (ˆx1): [0.37639 0.72617 0.57534]


In [78]:

# Construct matrix A2 = (A1 - ˆx1ˆxT1A1)
A2 = matrixA1 - np.outer(x1_hat, x1_hat) @ matrixA1

np.set_printoptions(precision=5, suppress=True)

# print("A2 : ",A2)
# Run the power method on A2
lambda_2, x2 = power_method(A2)

x2_hat = x2 / np.linalg.norm(x2, 2)
# Display the results for A2
print("\nFinal Results:")
print(f"Largest Eigenvalue (λ1): {lambda_2:.5f}")
print(f"Corresponding Eigenvector (x2): {x2}")
print(f"Normalized eigenvector (ˆx2): {x2_hat}")


Iteration 1: Eigenvalue = 3.11052 X = [ 0.89486 -1.25611  1.     ]
Iteration 2: Eigenvalue = 26.07740 X = [ 0.40543 -1.00243  1.     ]
Iteration 3: Eigenvalue = 22.87653 X = [ 0.30891 -0.95241  1.     ]
Iteration 4: Eigenvalue = 22.24532 X = [ 0.2866  -0.94084  1.     ]
Iteration 5: Eigenvalue = 22.09940 X = [ 0.28126 -0.93807  1.     ]
Iteration 6: Eigenvalue = 22.06448 X = [ 0.27997 -0.93741  1.     ]
Iteration 7: Eigenvalue = 22.05605 X = [ 0.27966 -0.93724  1.     ]
Iteration 8: Eigenvalue = 22.05402 X = [ 0.27959 -0.9372   1.     ]
Iteration 9: Eigenvalue = 22.05352 X = [ 0.27957 -0.9372   1.     ]
Iteration 10: Eigenvalue = 22.05340 X = [ 0.27957 -0.93719  1.     ]

Final Results:
Largest Eigenvalue (λ1): 22.05340
Corresponding Eigenvector (x2): [ 0.27957 -0.93719  1.     ]
Normalized eigenvector (ˆx2): [ 0.19987 -0.67002  0.71493]


In [79]:


# Construct matrix A3 = (A1 - ˆx1ˆxT1A1 - ˆx2ˆxT2A1)
A3 = matrixA1 - np.outer(x1_hat, x1_hat) @ matrixA1 - np.outer(x2_hat, x2_hat) @ matrixA1

# print("A3 : ",A3)

# Run the power method on A3
lambda_3, x3 = power_method(A3)

x3_hat = x3 / np.linalg.norm(x3, 2)

# Display the results for A3
print("\nFinal Results:")
print(f"Largest Eigenvalue (λ3): {lambda_3:.5f}")
print(f"Corresponding Eigenvector (x3): {x3}")
print(f"Normalized eigenvector (ˆx3): {x3_hat}")


Iteration 1: Eigenvalue = 1.70458 X = [ 1.      -0.17034 -0.43921]
Iteration 2: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]
Iteration 3: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]
Iteration 4: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]
Iteration 5: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]
Iteration 6: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]
Iteration 7: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]
Iteration 8: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]
Iteration 9: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]
Iteration 10: Eigenvalue = 5.33446 X = [ 1.      -0.17034 -0.43921]

Final Results:
Largest Eigenvalue (λ3): 5.33446
Corresponding Eigenvector (x3): [ 1.      -0.17034 -0.43921]
Normalized eigenvector (ˆx3): [ 0.90465 -0.1541  -0.39733]
